//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InterpersonalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InterpersonalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.InterpersonalResource", typeof(InterpersonalResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [name] is an altruist person kean to help others and offer their help without having others to ask them or wait to see if their help is really required and cares for others needs..
        /// </summary>
        internal static string AltruismHigh {
            get {
                return ResourceManager.GetString("AltruismHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [name] is much more oriented towards its own person. Does not care much about others..
        /// </summary>
        internal static string AltruismLow {
            get {
                return ResourceManager.GetString("AltruismLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [name] will help other coleagues if needed, but the chances are very low to offer to help others on their own..
        /// </summary>
        internal static string AltruismMed {
            get {
                return ResourceManager.GetString("AltruismMed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For {0}, cooperation seems almost as if it were something natural. It&apos;s easy to communicate with others and cooperating towards achieving a common goal seems to work very well for {0}..
        /// </summary>
        internal static string CooperationHigh {
            get {
                return ResourceManager.GetString("CooperationHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could significantly improve their ability to communicate and work together with others. As for the moment, cooperation is definitely a point to improve..
        /// </summary>
        internal static string CooperationLow {
            get {
                return ResourceManager.GetString("CooperationLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seems to handle communication with other people quite well. Nothing special, but capable to cooperate with others towards achieving a goal..
        /// </summary>
        internal static string CooperationMed {
            get {
                return ResourceManager.GetString("CooperationMed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to very sociable person. Easily integrating in new groups..
        /// </summary>
        internal static string GregarHigh {
            get {
                return ResourceManager.GetString("GregarHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a lonelier person, that feels comfortable to be on its own, rather than appealing to a group..
        /// </summary>
        internal static string GregarLow {
            get {
                return ResourceManager.GetString("GregarLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sociable person that easily associates with other persons and new groups..
        /// </summary>
        internal static string GregarMed {
            get {
                return ResourceManager.GetString("GregarMed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regarding the likelyhood for {0} to interact with coleagues, it appears to be {1}. {2}. We have taken a look on how altruist the candidate is and we found rather {3} results..
        /// </summary>
        internal static string Paragraph2 {
            get {
                return ResourceManager.GetString("Paragraph2", resourceCulture);
            }
        }
    }
}
