//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PersonalMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PersonalMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.PersonalMessages", typeof(PersonalMessages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seems like a person oriented to achieving
        ///more than it is expected. It makes efforts to achieve what is needed..
        /// </summary>
        public static string AchievmentStriving {
            get {
                return ResourceManager.GetString("AchievmentStriving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rather impressive, as he seems to speak as this would be important to achieve..
        /// </summary>
        public static string DutifulnessHigh {
            get {
                return ResourceManager.GetString("DutifulnessHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unexpectedly lower that usual and would be a real concern,
        ///considering the need for fulfilling duties..
        /// </summary>
        public static string DutifulnessLow {
            get {
                return ResourceManager.GetString("DutifulnessLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to normal, does not seem to have a special orientation towards fulfilling tasks
        ///in any special maner..
        /// </summary>
        public static string DutifulnessMedium {
            get {
                return ResourceManager.GetString("DutifulnessMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a rather quite intelligent and calculated person..
        /// </summary>
        public static string IntelectHigh {
            get {
                return ResourceManager.GetString("IntelectHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a rather not intellectual person, but has other qualities..
        /// </summary>
        public static string IntelectLow {
            get {
                return ResourceManager.GetString("IntelectLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a mediocre person considering his intelligence through the way he also formulates
        ///his answers..
        /// </summary>
        public static string IntelectMedium {
            get {
                return ResourceManager.GetString("IntelectMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to be a very modest person. When he talks about his achievments or strengths, he
        ///does not talk as if it was only his achievment but give credit to others..
        /// </summary>
        public static string ModestyHigh {
            get {
                return ResourceManager.GetString("ModestyHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to need to work on his attitude a bit more. Modesty is not one
        ///of his strengths and is rather low..
        /// </summary>
        public static string ModestyLow {
            get {
                return ResourceManager.GetString("ModestyLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to be a modest person. He cares about others but he does not necesarely miss an
        ///opportunity to brag with something he did..
        /// </summary>
        public static string ModestyMedium {
            get {
                return ResourceManager.GetString("ModestyMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After analyzing the answers, here are the results. {0} seems to {1}. The way he speaks classifies him as {2}. As an individual, his task orientation is {3}. {4}.
        /// </summary>
        public static string Paragraph1 {
            get {
                return ResourceManager.GetString("Paragraph1", resourceCulture);
            }
        }
    }
}
